AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  send_mail_from_lambda

  Sample SAM Template for send_mail_from_lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  SendMailFromLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: SendMailFromLambda
      CodeUri: send_mail_from_lambda/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Environment:
        Variables:
          Env: !Ref Env
          SES_URL: None
          TO_ADDRESSES: None
          FROM_ADDRESS: None

Parameters:
  # prod：本番環境 dev：開発環境（ローカル）
  Env:
    Type: String
    AllowedValues:
      - prod
      - dev
    Default: dev

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SendMailFromLambdaFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SendMailFromLambdaFunction.Arn
  SendMailFromLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SendMailFromLambdaFunctionRole.Arn
